/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RestaurantInfo = IDL.Record({
  'name' : IDL.Text,
  'instagramUrl' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
  'submitContactInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RestaurantInfo = IDL.Record({
    'name' : IDL.Text,
    'instagramUrl' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
    'submitContactInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };